#!/bin/sh
# The one place the Dolphin configure options live. Both flavors source this;
# they differ ONLY in toolchain. Vendored everything, no host subsystems, no
# UI, no networking backends, no achievements, no real audio/input/video
# devices. See docs/PLAN.md.
DOLPHIN_OPTS="
-DCMAKE_BUILD_TYPE=Release
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON
-DUSE_SYSTEM_LIBS=OFF
-DENABLE_QT=OFF
-DENABLE_NOGUI=OFF
-DENABLE_TESTS=OFF
-DENABLE_CLI_TOOL=OFF
-DUSE_RETRO_ACHIEVEMENTS=OFF
-DENABLE_SDL=OFF
-DENABLE_EVDEV=OFF
-DENABLE_X11=OFF
-DENABLE_EGL=OFF
-DENABLE_HWDB=OFF
-DENABLE_ANALYTICS=OFF
-DENABLE_AUTOUPDATE=OFF
-DENABLE_VULKAN=OFF
-DUSE_DISCORD_PRESENCE=OFF
-DENABLE_LLVM=OFF
-DUSE_MGBA=OFF
-DENABLE_HEADLESS=ON
-DENABLE_ALSA=OFF
-DENABLE_PULSEAUDIO=OFF
-DENABLE_CUBEB=OFF
-DUSE_UPNP=OFF
-DENCODE_FRAMEDUMPS=OFF
-DUSE_LIBUSB=OFF
-DUSE_CPPIPC=OFF
-DUSE_FSWATCHER=OFF
-DUSE_HIDAPI=OFF
-DBUILD_TRAVERSAL_SERVER=OFF
"
