#!/usr/bin/env python3
"""Derive the curated source list (sources.mk) from a survey CMake configure.

Dolphin's CMake is the authority on which files build on linux-x86_64; this
script mines its compile_commands.json and applies our exclusions, so the
curated list is reproducible instead of hand-typed. Run it once per upstream
bump:

  cmake -B <survey> [the trimmed -D set, see docs/PLAN.md] extern/dolphin
  python3 gen-sources.py <survey>/compile_commands.json > sources.mk

The exclusions each carry their reason; a file excluded here that the link
still wants gets a stub in stubs/, never a deletion patch.
"""
import json
import re
import sys

# path prefix (after Source/Core/ or Externals/) -> reason
EXCLUDE = {
    # not part of the core at all
    "DolphinTool/": "the cli tool, not the emulator",
    # networking: the box has no sockets, netplay/traversal never run
    "Core/NetPlayClient.cpp": "netplay - stubbed query surface in stubs/",
    "Core/NetPlayServer.cpp": "netplay",
    "Core/NetPlayCommon.cpp": "netplay",
    "Core/SyncIdentifier": "netplay",
    "Common/TraversalClient.cpp": "netplay traversal",
    "Core/HW/EXI/BBA/": "broadband adapter backends (sockets, SFML, cpp-ipc)",
    # real hardware access
    "Core/HW/WiimoteReal/IO": "real wiimote transports (bluetooth/hidapi)",
    "Core/GCAdapter.cpp": "libusb GC adapter - stubbed in stubs/",
    # host-side conveniences that leak host state
    "Core/MemoryWatcher.cpp": "USE_MEMORYWATCHER host pipe",
    "Core/PipeReader.cpp": "USE_PIPES host pipe",
    # GL glue arrives with the GPU bridge milestone, not before
    "Common/GL/": "host GL context glue - the bridge replaces it (M5)",
    "VideoBackends/OGL/": "the OGL backend joins at M5 via the bridge",
    "VideoCommon/Spirv.cpp": "glslang/SPIRV - no backend in the box wants it",
    # audio backends: the mixer is drained by the adapter instead
    "AudioCommon/AlsaSoundStream.cpp": "host audio",
    "AudioCommon/PulseAudioStream.cpp": "host audio",
    "AudioCommon/CubebStream.cpp": "host audio",
    "AudioCommon/CubebUtils.cpp": "host audio",
    "AudioCommon/OpenALStream.cpp": "host audio",
    "AudioCommon/OpenSLESStream.cpp": "host audio",
    "AudioCommon/WASAPIStream.cpp": "host audio",
    "AudioCommon/SurroundDecoder.cpp": "FreeSurround - never configured",
    # host input backends: input arrives from the frontend wire instead
    "InputCommon/ControllerInterface/evdev/": "host input",
    "InputCommon/ControllerInterface/Pipes/": "host input",
    "InputCommon/ControllerInterface/DualShockUDPClient/": "SFML sockets",
    "InputCommon/ControllerInterface/SDL/": "host input",
    "InputCommon/ControllerInterface/SteamDeck/": "hidapi",
    "InputCommon/GCAdapterConfigDiag": "libusb ui",
    # misc host-only
    "UICommon/DiscordPresence.cpp": "discord",
    "UICommon/AutoUpdate.cpp": "updater",
    # externals that only the excluded files wanted
    "ext:SFML": "sockets for netplay/BBA",
    "ext:enet": "netplay",
    "ext:cpp-ipc": "BBA IPC",
    "ext:cubeb": "host audio",
    "ext:libusb": "real usb",
    "ext:hidapi": "real hid",
    "ext:glslang": "SPIRV compiler for backends we exclude",
    "ext:FreeSurround": "surround decoding",
    "ext:cpp-optparse": "the cli tool's option parser",
}


def keep(rel: str) -> bool:
    return not any(rel.startswith(p) or (p.startswith("ext:") and rel.startswith("Externals/" + p[3:] + "/"))
                   for p in EXCLUDE)


def main() -> None:
    cc = json.load(open(sys.argv[1]))
    srcs, dropped = [], []
    for e in cc:
        f = e["file"]
        m = re.search(r"/(Source/Core/.+|Externals/.+)$", f)
        if not m:
            continue
        rel = m.group(1)
        rel_key = rel.removeprefix("Source/Core/") if rel.startswith("Source/Core/") else rel
        (srcs if keep(rel_key) else dropped).append(rel)
    srcs = sorted(set(srcs))
    print("# GENERATED by gen-sources.py from a survey configure of the pinned")
    print("# upstream - regenerate on every upstream bump, do not hand-edit the")
    print("# list. Exclusions and their reasons live in gen-sources.py.")
    print(f"# {len(srcs)} sources kept, {len(set(dropped))} dropped.")
    print()
    print("DOLPHIN_SRCS := \\")
    for s in srcs:
        print(f"  $(DP)/{s} \\")
    print()


if __name__ == "__main__":
    main()
